apiVersion: v1
kind: Service
metadata:
  name: deepfence-backend
  labels:
    {{- include "threatstryker-saas.labels" . | nindent 4 }}
    app: deepfence-console
    name: deepfence-backend
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - name: deepfence-backend-port
      port: 4041
      protocol: TCP
      targetPort: 4041

  selector:
    {{- include "threatstryker-saas.selectorLabels" . | nindent 4 }}
    name: deepfence-backend