---
apiVersion: v1
kind: Service
metadata:
  name: deepfence-api
  labels:
    {{- include "threatstryker-saas.labels" . | nindent 4 }}
    app: deepfence-console
    name: deepfence-api
  namespace: {{ .Values.namespace }}
spec:
  type:  {{ .Values.api.service.type }}
  selector:
    name: deepfence-api
  ports:
    - name: deepfence-api-port
      port: 9998
      protocol: TCP
      targetPort: 9998
    - name: deepfence-internal-api-port
      port: 9997
      protocol: TCP
      targetPort: 9997
