apiVersion:  apps/v1
kind: Deployment
metadata:
  name: deepfence-vulnerability-mapper
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
    app: deepfence-console
    name: deepfence-vulnerability-mapper
spec:
  {{- if not .Values.vulnerabilityMapper.autoscaling.enabled }}
  replicas: {{ .Values.vulnerabilityMapper.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      name: deepfence-vulnerability-mapper
      {{- include "deepfence-console.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: deepfence-console
        name: deepfence-vulnerability-mapper
        {{- include "deepfence-console.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      containers:
        - image: "{{ .Values.registry.imagePrefix }}{{ .Values.vulnerabilityMapper.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.vulnerabilityMapper.image.pullPolicy }}
          name: deepfence-vulnerability-mapper
          ports:
          - containerPort: 8001
          {{- if .Values.saas_deployment }}
          env:
              - name: CUSTOMER_UNIQUE_ID
                valueFrom:
                  secretKeyRef:
                    name: "es-secret-{{ include "deepfence-console.fullname" . }}"
                    key: es_customer_unique_id
          {{- end }}
          resources:
            {{- toYaml .Values.vulnerabilityMapper.resources | nindent 12 }}
      {{- with .Values.vulnerabilityMapper.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.vulnerabilityMapper.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
