name: ci

on:
  push:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags
  pull_request:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GROUP: deepfence
      COMMIT: ${{ github.sha }}
      REPO: demo-app
      DEEPFENCE_CONSOLE_IP: 127.0.0.1
      DEEPFENCE_KEY: key
    steps:
    - uses: actions/checkout@v2

    # Build docker image for service
    - name: Build docker image
      uses: docker/build-push-action@v1
      with:
        push: false
        repository: ${{ env.GROUP }}/${{ env.REPO }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}

    # Run Deepfence Vulnerability Mapper to check for vulnerabilities in image
    - name: Run Deepfence Vulnerability Mapper
      env:
        DEEPFENCE_CONSOLE_IP: ${{ env.DEEPFENCE_CONSOLE_IP }}
        DEEPFENCE_KEY: ${{ env.DEEPFENCE_KEY }}
        FULL_IMAGE_NAME: ${{ env.GROUP }}/${{ env.REPO }}:${{ github.sha }}
        FAIL_CVE_COUNT: 253 # Fail build if number of vulnerabilities found is >= this number. Set -1 to pass regardless of vulnerabilities.
        FAIL_CRITICAL_CVE_COUNT: 34 # Fail build if number of critical vulnerabilities found is >= this number. Set -1 to pass regardless of critical vulnerabilities.
        FAIL_HIGH_CVE_COUNT: 93 # Fail build if number of high vulnerabilities found is >= this number. Set -1 to pass regardless of high vulnerabilities.
        FAIL_MEDIUM_CVE_COUNT: 110 # Fail build if number of medium vulnerabilities found is >= this number. Set -1 to pass regardless of medium vulnerabilities.
        FAIL_LOW_CVE_COUNT: 19 # Fail build if number of low vulnerabilities found is >= this number. Set -1 to pass regardless of low vulnerabilities.
        FAIL_CVE_SCORE: 11 # Fail build if cumulative CVE score is >= this value. Set -1 to pass regardless of cve score.
      run: |
        mkdir deepfence_docker
        docker_config_path="$(pwd)/deepfence_docker"
        docker_creds=$(echo -n "${{ secrets.DOCKER_USER }}:${{ secrets.DOCKER_PASS }}" | base64)
        echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$docker_creds\"}}}" > "$docker_config_path/config.json"
        docker --config "$docker_config_path" pull deepfenceio/deepfence_package_scanner_ce:sid-dev
        rm -rf deepfence_docker
        docker run -i --rm --net=host --privileged=true --cpus='0.3' -v /var/run/docker.sock:/var/run/docker.sock:rw deepfenceio/deepfence_package_scanner_ce:sid-dev -deepfence-key="$DEEPFENCE_KEY" -vulnerability-scan=true -output=table -mode=local -mgmt-console-url=$DEEPFENCE_CONSOLE_IP  -source="$FULL_IMAGE_NAME" -fail-on-count=$FAIL_CVE_COUNT -fail-on-critical-count=$FAIL_CRITICAL_CVE_COUNT -fail-on-high-count=$FAIL_HIGH_CVE_COUNT -fail-on-medium-count=$FAIL_MEDIUM_CVE_COUNT -fail-on-low-count=$FAIL_LOW_CVE_COUNT -fail-on-score=$FAIL_CVE_SCORE

    # Push to dockerhub
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        repository: ${{ env.GROUP }}/${{ env.REPO }}
        tag_with_ref: true
        tag_with_sha: true