name: malware-scanner

on:
  push:
    branches:
    - "*"
  pull_request:
    branches:
    - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GROUP: deepfence
      COMMIT: ${{ github.sha }}
      REPO: demo-app
      DEEPFENCE_CONSOLE_URL: 127.0.0.1
      DEEPFENCE_KEY: key
      DEEPFENCE_LICENSE: ""
      DEEPFENCE_PRODUCT: ""
    steps:
    - uses: actions/checkout@v2

    # Build docker image for service
    - name: Build docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: ${{ env.GROUP }}/${{ env.REPO }}:${{ github.sha }}

    # Run Deepfence Malware Scanner to check for malwares in image
    - name: Run Deepfence Malware Scanner
      env:
        DEEPFENCE_CONSOLE_URL: ${{ env.DEEPFENCE_CONSOLE_URL }}
        DEEPFENCE_KEY: ${{ env.DEEPFENCE_KEY }}
        FULL_IMAGE_NAME: ${{ env.GROUP }}/${{ env.REPO }}:${{ github.sha }}
        FAIL_MALWARE_COUNT: 100 # Fail build if number of malwares found is >= this number. Set -1 to pass regardless of malwares.
        FAIL_HIGH_MALWARE_COUNT: 10 # Fail build if number of high malwares found is >= this number. Set -1 to pass regardless of high malwares.
        FAIL_MEDIUM_MALWARE_COUNT: 20 # Fail build if number of medium malwares found is >= this number. Set -1 to pass regardless of medium malwares.
        FAIL_LOW_MALWARE_COUNT: 50 # Fail build if number of low malwares found is >= this number. Set -1 to pass regardless of low malwares.
        DEEPFENCE_LICENSE: ""
        DEEPFENCE_PRODUCT: ""
      run: |
        docker pull quay.io/deepfenceio/deepfence_malware_scanner_ce:2.5.2
        docker run -i --rm --net=host --privileged=true --cpus=\"0.3\" -v /var/run/docker.sock:/var/run/docker.sock:rw quay.io/deepfenceio/deepfence_malware_scanner_ce:2.5.2 -image-name "$FULL_IMAGE_NAME" -fail-on-count=$FAIL_MALWARE_COUNT -fail-on-high-count=$FAIL_HIGH_MALWARE_COUNT -fail-on-medium-count=$FAIL_MEDIUM_MALWARE_COUNT -fail-on-low-count=$FAIL_LOW_MALWARE_COUNT"

    # Push to dockerhub
    - name: Push to Docker Hub
      uses: docker/build-push-action@v4
      if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        tags: ${{ env.GROUP }}/${{ env.REPO }}:${{ github.sha }}