{{- if .Values.saas_deployment }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.awsALB.certArn }}
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: {{ .Values.awsALB.groupName }}
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=3600
    alb.ingress.kubernetes.io/wafv2-acl-arn: {{ .Values.awsALB.wafAnnotation }}
    external-dns.alpha.kubernetes.io/ttl: "60"
  name: {{ .Release.Namespace }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: alb
  rules:
  - host: {{ .Values.deepfenceUrl }}
    http:
      paths:
      - backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
        path: /
        pathType: Prefix
      - backend:
          service:
            name: deepfence-router
            port:
              number: 443
        path: /
        pathType: Prefix
{{- end }}
