{{- if .Values.ui.runUIPod }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepfence-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
    app: deepfence-console
    name: deepfence-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      name: deepfence-ui
      {{- include "deepfence-console.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: deepfence-console
        name: deepfence-ui
        {{- include "deepfence-console.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      containers:
        - name: deepfence-ui
          image: "{{ .Values.registry.imagePrefix }}{{ .Values.ui.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.ui.image.pullPolicy }}"
          ports:
            - containerPort: 4042
          env:
            - name: SAAS_DEPLOYMENT
              value: "{{ .Values.saas_deployment }}"
            - name: PASSWORD_LOGIN_ENABLED
              value: "true"
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
