apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepfence-secret-scaner
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
    app: deepfence-console
    name: deepfence-secret-scanner
spec:
  {{- if not .Values.secretScanner.autoscaling.enabled }}
  replicas: {{ .Values.secretScanner.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      name: deepfence-secret-scanner
      {{- include "deepfence-console.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: deepfence-console
        name: deepfence-secret-scanner
        {{- include "deepfence-console.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      containers:
        - name: deepfence-secret-scanner
          image: "{{ .Values.registry.imagePrefix }}{{ .Values.secretScanner.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.secretScanner.image.pullPolicy }}
          ports:
            - containerPort: 8011
          command: ["/home/deepfence/usr/SecretScanner"]
          {{- if .Values.saas_deployment }}
          env:
            - name: CUSTOMER_UNIQUE_ID
              valueFrom:
                secretKeyRef:
                  name: "es-secret-{{ include "deepfence-console.fullname" . }}"
                  key: es_customer_unique_id
          {{- end }}
          args: ["-config-path", "/home/deepfence/usr", "-http-port", "8011"]
          resources:
            {{- toYaml .Values.secretScanner.resources | nindent 12 }}
      {{- with .Values.secretScanner.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.secretScanner.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
