name: Build and push to docker

on:
 schedule:
    - cron: '0 20 * * 6'
jobs:
  ThreatMapper-GitHub-Actions-Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout ThreatMapper Repo
        uses: actions/checkout@v2
        with:
         repository: deepfence/ThreatMapper
         path: ThreatMapper

      - run: cd ThreatMapper
      - run: docker logout 
      - run: docker login --username=jo19in1 --password=${{ secrets.DOCKER_PASSWORD}}
      - run: IMAGE_REPOSITORY=jo19in1 ./build.sh

      - run: docker push deepfenceio/deepfence_api_ce:latest
      - run: docker push deepfenceio/deepfence_api_ce:latest
      - run: docker push deepfenceio/deepfence_ui_ce:latest
      - run: docker push deepfenceio/deepfence_fetcher_ce:latest
      - run: docker push deepfenceio/deepfence_discovery_ce:latest
      - run: docker push deepfenceio/deepfence_elastic_ce:latest
      - run: docker push deepfenceio/deepfence_router_ce:latest
      - run: docker push deepfenceio/deepfence_postgres_ce:latest
      - run: docker push deepfenceio/deepfence_redis_ce:latest
      - run: docker push deepfenceio/deepfence_discovery_ce:latest
      - run: docker push deepfenceio/deepfence_diagnosis_ce:latest
      - run: docker push deepfenceio/deepfence_vulnerability_mapper_ce:latest
      - run: docker push deepfenceio/deepfence_agent_ce:latest
      - run: docker logout 

    
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."