name: Deploy to k8s

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Show environment v2
        run: env | grep ^GITHUB
      - name: Show ref v2
        run: echo "===============> Version from $GITHUB_REF"
